### ISSUE TITLE
Connexion à l'API Hub'EAU

### ISSUE THREAD

**Issue by babastienne** [Georiviere/Georiviere-admin#107]

**Comment by LePetitTim** [comment]
> sur l'URL créée pour Opérations URI renvoyant vers hydroeaufrance, l'URL ne fonctionne pas avec le code de la station. En regardant, il faut prendre uniquement les 7 premiers chiffres du code station, possible ?

Je ne suis pas sure de comprendre la demande.
Sinous utilisons que 7 chiffres ce n'est plus le bon code de station

**Comment by thomaspnrhj** [comment]
Pour la station V241402001, dans l'URL, c'est le code site et pas le code station qu'il faut reprendre pour arriver sur sa fiche sur Hydro.eaufrance : https://www.hydro.eaufrance.fr/sitehydro/V2414020/series 
![image](https://github.com/Georiviere/Georiviere-admin/assets/19687397/a2ab0afd-2bb1-469f-8ca4-c27f393d404f)

**Comment by babastienne** [comment]
Corrigé mais à priori l'URL n'est pas fonctionnelle

**Comment by thomaspnrhj** [comment]
@babastienne tu as une URL en exemple pour que je regarde ?

**Comment by babastienne** [comment]
@thomaspnrhj ton commentaire avait été mal interprété par @LePetitTim, la PR #213 corrige le problème.

**Comment by thomaspnrhj** [comment]
Testé sur la 1.2.4 : toujours le problème d'URL

**Comment by babastienne** [comment]
@thomaspnrhj peux-tu préciser le problème ? Sur quel objet observe tu le problème ? Peux-tu mettre une capture d'écran / un contexte ?

**Comment by thomaspnrhj** [comment]
Même exemple que en haut : 
![image](https://github.com/Georiviere/Georiviere-admin/assets/19687397/1fb3cb85-eab8-4844-8272-24f4834fdb64)

**Comment by thomaspnrhj** [comment]
C'est observé sur toutes les stations hydro, il faut générer l'url avec le code site et pas le code station (ou sinon ne pas prendre les deux derniers chiffres du code station) : https://www.hydro.eaufrance.fr/sitehydro/V2414020/series

**Comment by babastienne** [comment]
De mon côté testé à l'instant, tout semble ok :

**Station temperature**

![image](https://github.com/Georiviere/Georiviere-admin/assets/16348048/3ecd7e4b-4fee-4089-9939-59e300f424aa)

**Station hydrometrie**

![image](https://github.com/Georiviere/Georiviere-admin/assets/16348048/00cec5c2-1f45-4191-a7bc-1cfdc609af43)

**Station qualité**

![image](https://github.com/Georiviere/Georiviere-admin/assets/16348048/eb20f888-cb1b-4acb-b440-547f7f81cdec)

**Station hydrobio**

![image](https://github.com/Georiviere/Georiviere-admin/assets/16348048/374145f5-6ced-4590-a833-6416e7e846b2)


Tout semble ok donc. Est-ce que tu as bien mis à jour les stations avec la commande d'import ?

**Comment by thomaspnrhj** [comment]
Merci de ton retour rapide, effectivement j'avais pas pensé à faire le réimport... Par contre comme mentionné ci-dessus, j'ai toujours cette alerte qui pour l'import des stations qualite :

 Import 617 stations from API https://hubeau.eaufrance.fr/api/v2/qualite_rivieres/station_pc?format=json&size=1000&code_departement=01
Traceback (most recent call last):
  File "/opt/georiviere-admin/manage.py", line 22, in <module>
    main()
  File "/opt/georiviere-admin/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/venv/lib/python3.9/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/georiviere-admin/georiviere/observations/management/commands/__init__.py", line 61, in handle
    self.create_or_update_stations(results, verbosity, with_parameters)
  File "/opt/georiviere-admin/georiviere/observations/management/commands/import_pcquality_stations.py", line 110, in create_or_update_stations
    parameter_tracking, parameter_tracking_created = ParameterTracking.objects.get_or_create(
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/opt/venv/lib/python3.9/site-packages/django/db/models/query.py", line 433, in get
    raise self.model.MultipleObjectsReturned(
georiviere.observations.models.MultipleObjectsReturned: get() returned more than one ParameterTracking -- it returned 3!
